let handler = m => m

handler.before = function (m) {
    let user = global.db.data.users[m.sender]
    let role = (user.level <= 3) ? 'Guerrero V'
      : ((user.level >= 3) && (user.level <= 6)) ? 'Guerriero IV'
      : ((user.level >= 6) && (user.level <= 9)) ? 'Guerriero III'
      : ((user.level >= 9) && (user.level <= 12)) ? 'Guerriero II'
      : ((user.level >= 12) && (user.level <= 15)) ? 'Guerriero I'
      : ((user.level >= 15) && (user.level <= 18)) ? 'Élite V'
      : ((user.level >= 18) && (user.level <= 21)) ? 'Élite IV'
      : ((user.level >= 21) && (user.level <= 24)) ? 'Élite III'
      : ((user.level >= 24) && (user.level <= 27)) ? 'Élite II'
      : ((user.level >= 27) && (user.level <= 30)) ? 'Élite I'
      : ((user.level >= 30) && (user.level <= 33)) ? 'Maestro V'
      : ((user.level >= 33) && (user.level <= 36)) ? 'Maestro IV'
      : ((user.level >= 36) && (user.level <= 39)) ? 'Maestro III'
      : ((user.level >= 39) && (user.level <= 42)) ? 'Maestro II'
      : ((user.level >= 42) && (user.level <= 45)) ? 'Maestro I'
      : ((user.level >= 45) && (user.level <= 48)) ? 'Gran Maestro V'
      : ((user.level >= 48) && (user.level <= 51)) ? 'Gran Maestro IV'
      : ((user.level >= 51) && (user.level <= 54)) ? 'Gran Maestro III'
      : ((user.level >= 54) && (user.level <= 57)) ? 'Gran Maestro II'
      : ((user.level >= 57) && (user.level <= 60)) ? 'Gran Maestro I'
      : ((user.level >= 60) && (user.level <= 63)) ? 'Epico V'
      : ((user.level >= 63) && (user.level <= 66)) ? 'Epico IV'
      : ((user.level >= 66) && (user.level <= 69)) ? 'Epico III'
      : ((user.level >= 69) && (user.level <= 71)) ? 'Epico II'
      : ((user.level >= 71) && (user.level <= 74)) ? 'Epico I'
      : ((user.level >= 74) && (user.level <= 77)) ? 'Legenda V'
      : ((user.level >= 77) && (user.level <= 80)) ? 'Legenda IV'
      : ((user.level >= 80) && (user.level <= 83)) ? 'Legenda III'
      : ((user.level >= 83) && (user.level <= 86)) ? 'Legenda II'
      : ((user.level >= 86) && (user.level <= 89)) ? 'Legenda I'
      : ((user.level >= 89) && (user.level <= 91)) ? 'Mitico V'
      : ((user.level >= 91) && (user.level <= 94)) ? 'Mitico IV'
      : ((user.level >= 94) && (user.level <= 97)) ? 'Mitico III'
      : ((user.level >= 97) && (user.level <= 100)) ? 'Mitico II'
      : ((user.level >= 100) && (user.level <= 105)) ? 'Mitico I'      
      : ((user.level >= 105) && (user.level <= 120)) ? 'Gloria Mitica'
      : ((user.level >= 120) && (user.level <= 150)) ? 'Leggendario V'
      : ((user.level >= 150) && (user.level <= 160)) ? 'Leggendario VI'
      : ((user.level >= 160) && (user.level <= 170)) ? 'Leggendario III'
      : ((user.level >= 170) && (user.level <= 185)) ? 'Leggendario II'
      : ((user.level >= 185) && (user.level <= 200)) ? 'Leggendario I'
      : ((user.level >= 200) && (user.level <= 400)) ? 'Titano III'
      : ((user.level >= 405) && (user.level <= 700)) ? 'Titano II'
      : ((user.level >= 700) && (user.level <= 1000)) ? 'Titano I'
      : 'Re drago stellare'

    user.role = role
    return true
}

export default handler
